version: '3.8'

services:
  habbit_hero:
    build: .
    container_name: habbit-hero-app-compose
    ports:
      - "1488:8000"
    volumes:
      - ./characters:/app/characters
      - ./index.html:/app/index.html
      - ./css:/app/css
      - ./js:/app/js
    environment:
      - APP_INTERNAL_PORT=8000
    restart: unless-stopped